M48
; DRILL file {KiCad (6.0.11-0)} date Tuesday, 07 February 2023 at 21:04:20
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-07T21:04:20+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0768
%
G90
G05
T1
X1.9022Y-1.1795
X2.6522Y-1.7577
X3.4022Y-1.7577
X4.1522Y-1.1795
X4.1522Y-1.9295
T0
M30
